# Template to run hatch commands with databricks configured
name: hatch run with databricks configured
on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to (e.g., dev, prod)'
        required: true
        type: string
      workspace-setup:
        description: Json object containing workspace setup details
        required: false
        type: string
      
permissions:
  contents: read
  id-token: write

jobs: 
  apply_privileges:
    uses: ./.github/workflows/hatch.yaml
    with:
      environment: ${{ inputs.environment }}
      workspace-setup: ${{ inputs.workspace-setup }}
      command: 'apply_privileges:run'
    secrets: inherit