# Template to run hatch commands with databricks configured
name: hatch run with databricks configured
on:
  workflow_call:
    inputs:
      enviroment:
        description: 'The environment to deploy to (e.g., dev, prod)'
        required: true
        type: string
      workspace-setup:
        description: Json object containing workspace setup details
        required: false
        type: string
      command:
        description: 'The hatch command to run (e.g., deploy, test)'
        required: true
        type: string
        default: 'deploy'

permissions:
  contents: read
  id-token: write

jobs: 
  hatch:
    name: Run hatch command
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - run: python -m pip install pipx
        shell: bash
        name: Install pipx

      - run: python -m pipx ensurepath
        shell: bash
        name: Ensure pipx is in PATH

      - run: python -m pipx install hatch
        shell: bash
        name: Install hatch with pipx
      
      - run: python -m pipx inject hatch click==8.2.1 --force
        shell: bash
        name: Fix click version for hatch

      - name: hatch run ${{ inputs.command }}
        env:
          DATABRICKS_HOST: ${{ fromJson(vars.workspace_setup)[inputs.environment].host }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          ENVIRONMENT: ${{ inputs.environment }}
        run: hatch run ${{ inputs.command }}
        shell: bash