name: Apply Databrikcs privileges
on: 
  push:
    branches:
      - main
      - feat/**
  
  pull_request:
    branches:
      - '**'

permissions:
  contents: read
  id-token: write

jobs: 
  dev:
    needs: test_validate
    uses: ./.github/workflows/deploy_databricks.yml
    with:
      environment: 'dev'
    secrets: inherit