name: Apply Databrikcs privileges
on: 
  push:
    branches:
      - main
      - feat/**
  
  pull_request:
    branches:
      - '**'

permissions:
  contents: read
  id-token: write

jobs: 
  apply_privileges:
    uses: ./.github/workflows/apply_privileges.yaml
    with:
      environment: 'dev'
    secrets: inherit